--liquibase formatted sql

--changeset boomvox:003-create-album-table
CREATE TABLE album (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    genre VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_album PRIMARY KEY (id),
    CONSTRAINT fk_album_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

--rollback DROP TABLE IF EXISTS album;
