--liquibase formatted sql

--changeset boomvox:004-create-playlist-table
CREATE TABLE playlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_playlist PRIMARY KEY (id),
    CONSTRAINT fk_playlist_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

--rollback DROP TABLE IF EXISTS playlist;
