--liquibase formatted sql

--changeset boomvox:005-create-song-stats-table
CREATE TABLE song_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ratings_count BIGINT NOT NULL,
    avg_rating DOUBLE PRECISION NOT NULL,
    plays_count BIGINT NOT NULL,
    playlists_count BIGINT NOT NULL,
    recommendations_count BIGINT NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_song_stats PRIMARY KEY (id)
);

--rollback DROP TABLE IF EXISTS song_stats;
