--liquibase formatted sql

--changeset boomvox:006-create-song-table
CREATE TABLE song (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    album_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP(6) NOT NULL,
    format VARCHAR(255) NOT NULL,
    duration BIGINT NOT NULL,
    file_size BIGINT NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    song_stats_id BIGINT NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_song PRIMARY KEY (id),
    CONSTRAINT uq_song_song_stats UNIQUE (song_stats_id),
    CONSTRAINT fk_song_album FOREIGN KEY (album_id) REFERENCES album (id),
    CONSTRAINT fk_song_song_stats FOREIGN KEY (song_stats_id) REFERENCES song_stats (id)
);

--rollback DROP TABLE IF EXISTS song;
