--liquibase formatted sql

--changeset boomvox:007-create-tag-table
CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

--rollback DROP TABLE IF EXISTS tag;
