--liquibase formatted sql

--changeset boomvox:013-create-streaming-session-table
CREATE TABLE streaming_session (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    playlist_id BIGINT,
    started_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6),
    status VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_streaming_session PRIMARY KEY (id),
    CONSTRAINT fk_streaming_session_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT fk_streaming_session_song FOREIGN KEY (song_id) REFERENCES song (id),
    CONSTRAINT fk_streaming_session_playlist FOREIGN KEY (playlist_id) REFERENCES playlist (id)
);

--rollback DROP TABLE IF EXISTS streaming_session;
