spring.config.import=optional:file:aws.env[.properties]
#spring.config.import=optional:file:.env[.properties]

spring.application.name=boomvox
spring.ai.openai.api-key=${OPENAI_API_KEY}

aws.region=${aws.region}
aws.accessKeyId=${aws.accessKeyId}
aws.secretAccessKey=${aws.secretAccessKey}
aws.s3.bucket=${aws.s3.bucket}
aws.s3.signedUrlExpiryMinutes=${aws.s3.signedUrlExpiryMinutes:15}
