--liquibase formatted sql

--changeset boomvox:001-create-favourites-list-table
CREATE TABLE favourites_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_favourites_list PRIMARY KEY (id)
);

--rollback DROP TABLE IF EXISTS favourites_list;
