--liquibase formatted sql

--changeset boomvox:014-create-streaming-event-table
CREATE TABLE streaming_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id INTEGER NOT NULL,
    type VARCHAR(255) NOT NULL,
    position_sec BIGINT NOT NULL,
    seek_from_sec BIGINT,
    seek_to_sec BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_streaming_event PRIMARY KEY (id),
    CONSTRAINT fk_streaming_event_session FOREIGN KEY (session_id) REFERENCES streaming_session (id)
);

--rollback DROP TABLE IF EXISTS streaming_event;
