--liquibase formatted sql
--changeset boomvox:016-create-audio-variant-table

CREATE TABLE audio_variant (
                               id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               song_id          BIGINT        NOT NULL,
                               format           VARCHAR(255)  NOT NULL,
                               bitrate_kbps     INTEGER       NOT NULL,
                               duration_sec     INTEGER       NOT NULL,
                               file_size_bytes  BIGINT        NOT NULL,
                               storage_url      VARCHAR(1024) NOT NULL,
                               streaming_key    VARCHAR(1024) NOT NULL,
                               is_default       BOOLEAN       NOT NULL DEFAULT FALSE,
                               status           VARCHAR(255)  NOT NULL,
                               version          BIGINT        NOT NULL,
                               CONSTRAINT pk_audio_variant PRIMARY KEY (id),
                               CONSTRAINT fk_audio_variant_song FOREIGN KEY (song_id) REFERENCES song (id)
);

--rollback DROP TABLE IF EXISTS audio_variant;