--liquibase formatted sql

--changeset boomvox:018-create-listening-history-table
CREATE TABLE listening_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    session_id INTEGER NOT NULL,
    listened_at TIMESTAMP(6) NOT NULL,
    listened_duration_sec BIGINT NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_listening_history PRIMARY KEY (id),
    CONSTRAINT uq_listening_history_session UNIQUE (session_id),
    CONSTRAINT ck_listening_history_duration CHECK (listened_duration_sec >= 0),
    CONSTRAINT fk_listening_history_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT fk_listening_history_song FOREIGN KEY (song_id) REFERENCES song (id),
    CONSTRAINT fk_listening_history_session FOREIGN KEY (session_id) REFERENCES streaming_session (id)
);

CREATE INDEX ix_listening_history_user_listened_at
    ON listening_history (user_id, listened_at DESC);

CREATE INDEX ix_listening_history_song
    ON listening_history (song_id);

--rollback DROP TABLE IF EXISTS listening_history;
