--liquibase formatted sql

--changeset boomvox:002-create-user-table
CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    role VARCHAR(255) NOT NULL,
    favourites_list_id BIGINT,
    version BIGINT NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_username UNIQUE (username),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_favourites_list UNIQUE (favourites_list_id),
    CONSTRAINT fk_user_favourites_list
        FOREIGN KEY (favourites_list_id) REFERENCES favourites_list (id)
);

--rollback DROP TABLE IF EXISTS "user";
