spring:
  application:
    name: boomvox
  profiles:
    active: dev

server:
  port: 8099

boomvox:
  default-page-size: 10
  log-level: INFO
  log-file: logs/boomvox.log

logging:
  level:
    root: WARN
    bg.fmi.uni.boomvox: INFO